// Canonical 66-book list. `id` is used internally; `aliases` are input forms
// (English, abbreviated, German) accepted by the reference parser in bible.js.
// `kjv`/`de` are the display names used in the reference line, matched to the
// selected translation's language. Lookup is case-insensitive; leading "I "/
// "1st " style ordinals are normalized to "1 " before matching (see
// normalizeOrdinalPrefix below).
export const BOOKS = [
  {
    id: "GEN",
    deShort: "1 Mo",
    kjv: "Genesis",
    de: "1 Mose",
    schlachter: "Das erste Buch Mose (Genesis)",
    aliases: ["1 Mose", "Gen", "Genesis"],
  },
  {
    id: "EXO",
    deShort: "2 Mo",
    kjv: "Exodus",
    de: "2 Mose",
    schlachter: "Das zweite Buch Mose (Exodus)",
    aliases: ["2 Mose", "Ex", "Exodus"],
  },
  {
    id: "LEV",
    deShort: "3 Mo",
    kjv: "Leviticus",
    de: "3 Mose",
    schlachter: "Das dritte Buch Mose (Leviticus)",
    aliases: ["3 Mose", "Lev", "Leviticus"],
  },
  {
    id: "NUM",
    deShort: "4 Mo",
    kjv: "Numbers",
    de: "4 Mose",
    schlachter: "Das vierte Buch Mose (Numeri)",
    aliases: ["4 Mose", "Num", "Numbers"],
  },
  {
    id: "DEU",
    deShort: "5 Mo",
    kjv: "Deuteronomy",
    de: "5 Mose",
    schlachter: "Das fünfte Buch Mose (Deuteronomium)",
    aliases: ["5 Mose", "Deut", "Deuteronomy"],
  },
  {
    id: "JOS",
    deShort: "Jos",
    kjv: "Joshua",
    de: "Josua",
    schlachter: "Das Buch Josua",
    aliases: ["Josh", "Joshua", "Josua"],
  },
  {
    id: "JDG",
    deShort: "Ri",
    kjv: "Judges",
    de: "Richter",
    schlachter: "Das Buch der Richter",
    aliases: ["Judg", "Judges", "Richter"],
  },
  {
    id: "RUT",
    deShort: "Rut",
    kjv: "Ruth",
    de: "Ruth",
    schlachter: "Das Buch Ruth",
    aliases: ["Ruth"],
  },
  {
    id: "1SA",
    deShort: "1 Sam",
    kjv: "1 Samuel",
    de: "1 Samuel",
    schlachter: "Das erste Buch Samuel",
    aliases: ["1 Sam", "1 Samuel"],
  },
  {
    id: "2SA",
    deShort: "2 Sam",
    kjv: "2 Samuel",
    de: "2 Samuel",
    schlachter: "Das zweite Buch Samuel",
    aliases: ["2 Sam", "2 Samuel"],
  },
  {
    id: "1KI",
    deShort: "1 Kön",
    kjv: "1 Kings",
    de: "1 Könige",
    schlachter: "Das erste Buch der Könige",
    aliases: ["1 Kgs", "1 Kings", "1 Könige"],
  },
  {
    id: "2KI",
    deShort: "2 Kön",
    kjv: "2 Kings",
    de: "2 Könige",
    schlachter: "Das zweite Buch der Könige",
    aliases: ["2 Kgs", "2 Kings", "2 Könige"],
  },
  {
    id: "1CH",
    deShort: "1 Chr",
    kjv: "1 Chronicles",
    de: "1 Chronik",
    schlachter: "Das erste Buch der Chronik",
    aliases: ["1 Chr", "1 Chronicles", "1 Chronik"],
  },
  {
    id: "2CH",
    deShort: "2 Chr",
    kjv: "2 Chronicles",
    de: "2 Chronik",
    schlachter: "Das zweite Buch der Chronik",
    aliases: ["2 Chr", "2 Chronicles", "2 Chronik"],
  },
  {
    id: "EZR",
    deShort: "Esra",
    kjv: "Ezra",
    de: "Esra",
    schlachter: "Das Buch Esra",
    aliases: ["Esra", "Ezra"],
  },
  {
    id: "NEH",
    deShort: "Neh",
    kjv: "Nehemiah",
    de: "Nehemia",
    schlachter: "Das Buch Nehemia",
    aliases: ["Neh", "Nehemia", "Nehemiah"],
  },
  {
    id: "EST",
    deShort: "Est",
    kjv: "Esther",
    de: "Esther",
    schlachter: "Das Buch Esther",
    aliases: ["Esth", "Esther"],
  },
  {
    id: "JOB",
    deShort: "Hiob",
    kjv: "Job",
    de: "Hiob",
    schlachter: "Das Buch Hiob",
    aliases: ["Hiob", "Job"],
  },
  {
    id: "PSA",
    deShort: "Ps",
    kjv: "Psalms",
    de: "Psalmen",
    schlachter: "Die Psalmen",
    aliases: ["Ps", "Psalm", "Psalmen", "Psalms"],
  },
  {
    id: "PRO",
    deShort: "Spr",
    kjv: "Proverbs",
    de: "Sprüche",
    schlachter: "Die Sprüche",
    aliases: ["Prov", "Proverbs", "Sprüche"],
  },
  {
    id: "ECC",
    deShort: "Pred",
    kjv: "Ecclesiastes",
    de: "Prediger",
    schlachter: "Der Prediger",
    aliases: ["Eccl", "Ecclesiastes", "Prediger"],
  },
  {
    id: "SNG",
    deShort: "Hld",
    kjv: "Solomon's Song",
    de: "Hohelied",
    schlachter: "Das Hohelied",
    aliases: ["Hohelied", "Solomon's Song", "Song"],
  },
  {
    id: "ISA",
    deShort: "Jes",
    kjv: "Isaiah",
    de: "Jesaja",
    schlachter: "Das Buch des Propheten Jesaja",
    aliases: ["Isa", "Isaiah", "Jesaja"],
  },
  {
    id: "JER",
    deShort: "Jer",
    kjv: "Jeremiah",
    de: "Jeremia",
    schlachter: "Das Buch des Propheten Jeremia",
    aliases: ["Jer", "Jeremia", "Jeremiah"],
  },
  {
    id: "LAM",
    deShort: "Klgl",
    kjv: "Lamentations",
    de: "Klagelieder",
    schlachter: "Die Klagelieder Jeremias",
    aliases: ["Klagelieder", "Lam", "Lamentations"],
  },
  {
    id: "EZK",
    deShort: "Hes",
    kjv: "Ezekiel",
    de: "Hesekiel",
    schlachter: "Das Buch des Propheten Hesekiel (Ezechiel)",
    aliases: ["Ezek", "Ezekiel", "Hesekiel"],
  },
  {
    id: "DAN",
    deShort: "Dan",
    kjv: "Daniel",
    de: "Daniel",
    schlachter: "Das Buch des Propheten Daniel",
    aliases: ["Dan", "Daniel"],
  },
  {
    id: "HOS",
    deShort: "Hos",
    kjv: "Hosea",
    de: "Hosea",
    schlachter: "Das Buch des Propheten Hosea",
    aliases: ["Hos", "Hosea"],
  },
  {
    id: "JOL",
    deShort: "Joel",
    kjv: "Joel",
    de: "Joel",
    schlachter: "Das Buch des Propheten Joel",
    aliases: ["Joel"],
  },
  {
    id: "AMO",
    deShort: "Am",
    kjv: "Amos",
    de: "Amos",
    schlachter: "Das Buch des Propheten Amos",
    aliases: ["Amos"],
  },
  {
    id: "OBA",
    deShort: "Obd",
    kjv: "Obadiah",
    de: "Obadja",
    schlachter: "Das Buch des Propheten Obadja",
    aliases: ["Obad", "Obadiah", "Obadja"],
  },
  {
    id: "JON",
    deShort: "Jona",
    kjv: "Jonah",
    de: "Jona",
    schlachter: "Das Buch des Propheten Jona",
    aliases: ["Jona", "Jonah"],
  },
  {
    id: "MIC",
    deShort: "Mi",
    kjv: "Micah",
    de: "Micha",
    schlachter: "Das Buch des Propheten Micha",
    aliases: ["Mic", "Micah", "Micha"],
  },
  {
    id: "NAM",
    deShort: "Nah",
    kjv: "Nahum",
    de: "Nahum",
    schlachter: "Das Buch des Propheten Nahum",
    aliases: ["Nah", "Nahum"],
  },
  {
    id: "HAB",
    deShort: "Hab",
    kjv: "Habakkuk",
    de: "Habakuk",
    schlachter: "Das Buch des Propheten Habakuk",
    aliases: ["Hab", "Habakkuk", "Habakuk"],
  },
  {
    id: "ZEP",
    deShort: "Zef",
    kjv: "Zephaniah",
    de: "Zephanja",
    schlachter: "Das Buch des Propheten Zephanja",
    aliases: ["Zeph", "Zephaniah", "Zephanja"],
  },
  {
    id: "HAG",
    deShort: "Hag",
    kjv: "Haggai",
    de: "Haggai",
    schlachter: "Das Buch des Propheten Haggai",
    aliases: ["Hag", "Haggai"],
  },
  {
    id: "ZEC",
    deShort: "Sach",
    kjv: "Zechariah",
    de: "Sacharja",
    schlachter: "Das Buch des Propheten Sacharja",
    aliases: ["Sacharja", "Zech", "Zechariah"],
  },
  {
    id: "MAL",
    deShort: "Mal",
    kjv: "Malachi",
    de: "Maleachi",
    schlachter: "Das Buch des Propheten Maleachi",
    aliases: ["Mal", "Malachi", "Maleachi"],
  },
  {
    id: "MAT",
    deShort: "Mt",
    kjv: "Matthew",
    de: "Matthäus",
    schlachter: "Das Evangelium nach Matthäus",
    aliases: ["Matt", "Matthew", "Matthäus"],
  },
  {
    id: "MRK",
    deShort: "Mk",
    kjv: "Mark",
    de: "Markus",
    schlachter: "Das Evangelium nach Markus",
    aliases: ["Mark", "Markus"],
  },
  {
    id: "LUK",
    deShort: "Lk",
    kjv: "Luke",
    de: "Lukas",
    schlachter: "Das Evangelium nach Lukas",
    aliases: ["Lukas", "Luke"],
  },
  {
    id: "JHN",
    deShort: "Joh",
    kjv: "John",
    de: "Johannes",
    schlachter: "Das Evangelium nach Johannes",
    aliases: ["Johannes", "John"],
  },
  {
    id: "ACT",
    deShort: "Apg",
    kjv: "Acts",
    de: "Apostelgeschichte",
    schlachter: "Die Apostelgeschichte",
    aliases: ["Acts", "Apostelgeschichte"],
  },
  {
    id: "ROM",
    deShort: "Röm",
    kjv: "Romans",
    de: "Römer",
    schlachter: "Der Brief des Apostels Paulus an die Römer",
    aliases: ["Rom", "Romans", "Römer"],
  },
  {
    id: "1CO",
    deShort: "1 Kor",
    kjv: "1 Corinthians",
    de: "1 Korinther",
    schlachter: "Der erste Brief des Apostels Paulus an die Korinther",
    aliases: ["1 Cor", "1 Corinthians", "1 Korinther"],
  },
  {
    id: "2CO",
    deShort: "2 Kor",
    kjv: "2 Corinthians",
    de: "2 Korinther",
    schlachter: "Der zweite Brief des Apostels Paulus an die Korinther",
    aliases: ["2 Cor", "2 Corinthians", "2 Korinther"],
  },
  {
    id: "GAL",
    deShort: "Gal",
    kjv: "Galatians",
    de: "Galater",
    schlachter: "Der Brief des Apostels Paulus an die Galater",
    aliases: ["Gal", "Galater", "Galatians"],
  },
  {
    id: "EPH",
    deShort: "Eph",
    kjv: "Ephesians",
    de: "Epheser",
    schlachter: "Der Brief des Apostels Paulus an die Epheser",
    aliases: ["Eph", "Epheser", "Ephesians"],
  },
  {
    id: "PHP",
    deShort: "Phil",
    kjv: "Philippians",
    de: "Philipper",
    schlachter: "Der Brief des Apostels Paulus an die Philipper",
    aliases: ["Phil", "Philipper", "Philippians"],
  },
  {
    id: "COL",
    deShort: "Kol",
    kjv: "Colossians",
    de: "Kolosser",
    schlachter: "Der Brief des Apostels Paulus an die Kolosser",
    aliases: ["Col", "Colossians", "Kolosser"],
  },
  {
    id: "1TH",
    deShort: "1 Thess",
    kjv: "1 Thessalonians",
    de: "1 Thessalonicher",
    schlachter: "Der erste Brief des Apostels Paulus an die Thessalonicher",
    aliases: ["1 Thess", "1 Thessalonians", "1 Thessalonicher"],
  },
  {
    id: "2TH",
    deShort: "2 Thess",
    kjv: "2 Thessalonians",
    de: "2 Thessalonicher",
    schlachter: "Der zweite Brief des Apostels Paulus an die Thessalonicher",
    aliases: ["2 Thess", "2 Thessalonians", "2 Thessalonicher"],
  },
  {
    id: "1TI",
    deShort: "1 Tim",
    kjv: "1 Timothy",
    de: "1 Timotheus",
    schlachter: "Der erste Brief des Apostels Paulus an Timotheus",
    aliases: ["1 Tim", "1 Timotheus", "1 Timothy"],
  },
  {
    id: "2TI",
    deShort: "2 Tim",
    kjv: "2 Timothy",
    de: "2 Timotheus",
    schlachter: "Der zweite Brief des Apostels Paulus an Timotheus",
    aliases: ["2 Tim", "2 Timotheus", "2 Timothy"],
  },
  {
    id: "TIT",
    deShort: "Tit",
    kjv: "Titus",
    de: "Titus",
    schlachter: "Der Brief des Apostels Paulus an Titus",
    aliases: ["Titus"],
  },
  {
    id: "PHM",
    deShort: "Phlm",
    kjv: "Philemon",
    de: "Philemon",
    schlachter: "Der Brief des Apostels Paulus an Philemon",
    aliases: ["Philemon", "Phlm"],
  },
  {
    id: "HEB",
    deShort: "Hebr",
    kjv: "Hebrews",
    de: "Hebräer",
    schlachter: "Der Brief an die Hebräer",
    aliases: ["Heb", "Hebrews", "Hebräer"],
  },
  {
    id: "JAS",
    deShort: "Jak",
    kjv: "James",
    de: "Jakobus",
    schlachter: "Der Brief des Jakobus",
    aliases: ["Jakobus", "James", "Jas"],
  },
  {
    id: "1PE",
    deShort: "1 Petr",
    kjv: "1 Peter",
    de: "1 Petrus",
    schlachter: "Der erste Brief des Apostels Petrus",
    aliases: ["1 Pet", "1 Peter", "1 Petrus"],
  },
  {
    id: "2PE",
    deShort: "2 Petr",
    kjv: "2 Peter",
    de: "2 Petrus",
    schlachter: "Der zweite Brief des Apostels Petrus",
    aliases: ["2 Pet", "2 Peter", "2 Petrus"],
  },
  {
    id: "1JN",
    deShort: "1 Joh",
    kjv: "1 John",
    de: "1 Johannes",
    schlachter: "Der erste Brief des Apostels Johannes",
    aliases: ["1 Johannes", "1 John"],
  },
  {
    id: "2JN",
    deShort: "2 Joh",
    kjv: "2 John",
    de: "2 Johannes",
    schlachter: "Der zweite Brief des Apostels Johannes",
    aliases: ["2 Johannes", "2 John"],
  },
  {
    id: "3JN",
    deShort: "3 Joh",
    kjv: "3 John",
    de: "3 Johannes",
    schlachter: "Der dritte Brief des Apostels Johannes",
    aliases: ["3 Johannes", "3 John"],
  },
  {
    id: "JUD",
    deShort: "Jud",
    kjv: "Jude",
    de: "Judas",
    schlachter: "Der Brief des Judas",
    aliases: ["Judas", "Jude"],
  },
  {
    id: "REV",
    deShort: "Offb",
    kjv: "Revelation",
    de: "Offenbarung",
    schlachter: "Die Offenbarung Jesu Christi durch Johannes",
    aliases: ["Offenbarung", "Rev", "Revelation"],
  },
];

const ALIAS_MAP = new Map();
for (const book of BOOKS) {
  // `id` is the standard English 3-letter abbreviation (Mat, Deu, ...);
  // `deShort` is the equivalent short German form (Mt, 1 Mo, ...) - both
  // accepted as input directly, not just the full names in `aliases`.
  for (const alias of [book.id, book.deShort, book.kjv, ...book.aliases]) {
    ALIAS_MAP.set(alias.toLowerCase(), book);
  }
}

function normalizeOrdinalPrefix(input) {
  return input
    .replace(/^(i{1,3})\.?\s+/i, (_, roman) => `${['i', 'ii', 'iii'].indexOf(roman.toLowerCase()) + 1} `)
    .replace(/^(\d)(st|nd|rd|th)\.?\s+/i, '$1 ');
}

export function findBook(input) {
  const key = normalizeOrdinalPrefix(input.trim()).toLowerCase();
  return ALIAS_MAP.get(key) || null;
}

// "MAT" -> "Mat", "1SA" -> "1Sa" - title-cases an all-caps id for display.
function titleCaseId(id) {
  return id.replace(/^(\d?)([A-Z])([A-Z]*)/, (_, digit, first, rest) => `${digit}${first}${rest.toLowerCase()}`);
}

// The short form a parsed reference gets rewritten to once resolved (see
// updateVerse in main.js) - the English 3-letter id for KJV, or the
// equivalent short German form for Schlachter, so it matches whichever
// language the user is actually reading in.
export function shortBookLabel(book, translation) {
  return translation === "schlachter" ? book.deShort : titleCaseId(book.id);
}
